#!/usr/bin/env bash
set -euo pipefail

# Print a per-slot .env overlay for Tango parallel worktrees.
usage() {
  echo "Usage: $0 <slot: 1|2|3>" >&2
  exit 1
}

if [ "$#" -ne 1 ]; then
  usage
fi

slot="$1"

case "$slot" in
  1|2|3) ;;
  *)
    echo "Invalid slot '$slot'. Expected 1, 2, or 3." >&2
    exit 1
    ;;
esac

cat <<EOF
# Tango parallel worktree slot overlay (slot $slot)
# Source after .env (not instead of). Generated by scripts/dev/slot-env.sh.
export TANGO_PROFILE=wt-$slot
export TANGO_SLOT=$slot
export TANGO_VOICE_BRIDGE_ENABLED=false
# Phase 2 will add: DISCORD_TOKEN (from 1Password), DISCORD_ALLOWED_CHANNELS, DISCORD_TEST_CHANNEL_ID (thread)
EOF
